# 认证模块开始配置
authentication:
  # 是否启用认证模块的自动配置
  enable: true
  # 反暴破配置
  antiBruteCrack:
    # 最大尝试授权次数
    maxCrackTimes: 10
    # 如果触发反暴破规则，则禁用账号的时长
    banDuration: 1d
  # MVC配置
  mvc:
    # 是否启用MVC的自动配置
    enable: true
    # 认证凭证的请求头
    header: Authentication
    # 包含认证检查的接口路径
    includePaths: ['/api/**']
    # 排除认证检查的接口路径
    excludePaths: ['/api/public/**']
